spring:
  application:
    name: sun-rise

  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/mock_project
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  logging:
    level:
      org:
        springframework:
          security: DEBUG
          aop: DEBUG

server:
  port: 8086
  servlet:
    context-path: /sun

application:
  admin:
    default:
      username: sunrise
      password: test1234