# application.yml

spring:
  application:
    name: sun-rise

  datasource:
    url: jdbc:postgresql://ep-orange-lake-a504982s.us-east-2.aws.neon.tech/thanh-binh
    username: sun
    password: ameHN4MXxVQ5
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: tranquangg.1108@gmail.com
    password: qsnt yxbi yjud fcpf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  logging:
    level:
      org:
        springframework:
          security: DEBUG
          aop: DEBUG

server:
  port: 8086
  servlet:
    context-path: /sun
    session:
      timeout: 30s

application:
  admin:
    default:
      username: sunrise
      password: test1234
      firstname: james
      lastname: bonds
      email: sun@sun.com

user:
  avatar:
    directory: /path/to/avatars

default:
  admin-create-key: dfjkNdkMAnje
  encode-key: abcdefghabcdefgh
  type-encode: AES
  recaptcha-site-key: 6LfblD0qAAAAAC1k-Zd8GfiyXmKjNWBV4xMC1BNP
  captcha-enable: true
  recaptcha-secret-key: 6LfblD0qAAAAAO2lT_e5JwmxUFJ55uCpxPrdwk0T
