spring:
  application:
    name: sun-rise
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SERVER}
    password: ${PASSWORD_EMAIL_SERVER}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  logging:
    level:
      org:
        springframework:
          security: DEBUG
          aop: DEBUG

server:
  port: ${SERVER_LOCAL_PORT}
  servlet:
    context-path: /sun
    session:
      timeout: 3600s

logging:
  level:
    org:
      springframework:
        security: INFO

application:
  admin:
    default:
      username: ${ADMIN_DEFAULT_USERNAME}
      password: ${ADMIN_DEFAULT_PASSWORD}
      firstname: ${ADMIN_DEFAULT_FIRST}
      lastname: ${ADMIN_DEFAULT_LAST}
      email: ${ADMIN_DEFAULT_EMAIL}

default:
  admin-create-key: ${ADMIN_CREATE_KEY}
  encode-key: ${ENCODE_KEY}
  type-encode: ${TYPE_ENCODE}
  recaptcha-secret-key: ${RECAPTCHA_SECRET_KEY}
  recaptcha-site-key: ${RECAPTCHA_SITE_KEY}
  captcha-enable: ${CAPTCHA_ENABLE}
  timing-send-mail: ${TIMING_SEND_EMAIL}

storage:
  path: ${STORAGE_PATH}